import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { Suspense } from "react";
import "./globals.scss";

import AuthProvider from "@/components/AuthProvider";
import ConditionalLayout from "@/components/ConditionalLayout";
import ScrollToTop from "@/components/common/ScrollToTop";
import ConnectAIWrapper from "@/components/connect/ConnectAIWrapper";
import IntroVideo from "@/components/common/IntroVideo";

const netflixSans = localFont({
  src: [
    { path: "./fonts/NetflixSansThin.ttf", weight: "100" },
    { path: "./fonts/NetflixSansLight.ttf", weight: "300" },
    { path: "./fonts/NetflixSansRegular.ttf", weight: "400" },
    { path: "./fonts/NetflixSansMedium.ttf", weight: "500" },
    { path: "./fonts/NetflixSansBold.ttf", weight: "700" },
    { path: "./fonts/NetflixSansBlack.ttf", weight: "900" },
  ],
  variable: "--font-netflix",
});

export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by Netflix",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent", // 상단 상태바를 검은색으로 처리
    title: "Netflix",
  },
  icons: {
    apple: "/icons/icon-192x192.png", // 아이폰 홈 화면 추가 시 사용될 아이콘
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1, // 앱처럼 동작하게 하기 위해 줌 제한
  userScalable: false,
  viewportFit: "cover",
  colorScheme: "dark",
  themeColor: "#000000", // 브라우저 상단바 색상
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body className={netflixSans.variable}>
        {/* ... */}
        <IntroVideo />
        <AuthProvider>
          <Suspense fallback={null}>
            <ScrollToTop />
          </Suspense>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
          {/* 래퍼를 통해 안전하게 렌더링 */}
          <ConnectAIWrapper />
        </AuthProvider>
      </body>
    </html>
  );
}
